# -*- coding: utf-8 -*-
"""Parche v2: restaura desde backup y aplica fix correcto."""
import os, shutil, sys, time

ROOT = os.path.dirname(os.path.abspath(__file__))
APP_PY = os.path.join(ROOT, "informe_web", "app.py")
BASE_HTML = os.path.join(ROOT, "informe_web", "templates", "base.html")
BACKUP = os.path.join(ROOT, "_patch_backup")

print("=== Parche v2 - Fix regex update check ===")

# 1. Restaurar desde backup
bak = os.path.join(BACKUP, "app.py.bak")
if not os.path.exists(bak):
    print("ERROR: No hay backup en _patch_backup/app.py.bak")
    sys.exit(1)

shutil.copy2(bak, APP_PY)
print("[OK] app.py restaurado desde backup")

# 2. Leer
with open(APP_PY, "r", encoding="utf-8") as f:
    code = f.read()

# 3. Reemplazar api_actualizacion
idx1 = code.find("def api_actualizacion()")
idx2 = code.find("def aplicar_actualizacion()")
if idx1 == -1 or idx2 == -1:
    print("ERROR: No se encontraron las funciones")
    sys.exit(1)

new_api = []
new_api.append('def api_actualizacion():')
new_api.append('        """Consulta la release mas reciente publicada en GitHub.')
new_api.append('        Estrategia: gh CLI primero; REST API publica como fallback."""')
new_api.append('        if not es_admin_actual():')
new_api.append('            return jsonify({"error": "No autorizado"}), 403')
new_api.append('        repo = app.config.get("INFORME_REPO", "jacj01/informe-mensual-obra")')
new_api.append('        local_v = app.config.get("INFORME_VERSION", "1.0.0")')
new_api.append('')
new_api.append('        def _vt(s):')
new_api.append('            import re')
new_api.append('            m = re.search(r"v?(\\d+\\.\\d+\\.\\d+)", s or "")')
new_api.append('            return tuple(int(x) for x in m.group(1).split(".")) if m else (0, 0, 0)')
new_api.append('')
new_api.append('        data = None')
new_api.append('        tag = ""')
new_api.append('')
new_api.append('        try:')
new_api.append('            import subprocess, re')
new_api.append('            cmd = ["gh", "-R", repo, "release", "view", "--json",')
new_api.append('                   "tagName,name,publishedAt,assets"]')
new_api.append('            out = subprocess.run(cmd, capture_output=True, text=True, timeout=15,')
new_api.append('                                 creationflags=0x08000000)')
new_api.append('            if out.returncode == 0 and out.stdout.strip():')
new_api.append('                raw = json.loads(out.stdout)')
new_api.append('                tag = raw.get("tagName", "")')
new_api.append('                asset = next((a for a in raw.get("assets", [])')
new_api.append('                              if a.get("name", "").endswith(".zip")), None)')
new_api.append('                data = {')
new_api.append('                    "tag": tag,')
new_api.append('                    "nombre": raw.get("name", ""),')
new_api.append('                    "publicada": raw.get("publicatedAt", ""),')
new_api.append('                    "asset": asset.get("name") if asset else None,')
new_api.append('                    "url": asset.get("url") if asset else None,')
new_api.append('                }')
new_api.append('        except Exception:')
new_api.append('            data = None')
new_api.append('')
new_api.append('        if data is None:')
new_api.append('            try:')
new_api.append('                import urllib.request, urllib.error, ssl')
new_api.append('                api_url = "https://api.github.com/repos/" + repo + "/releases/latest"')
new_api.append('                req = urllib.request.Request(api_url)')
new_api.append('                req.add_header("Accept", "application/vnd.github+json")')
new_api.append('                req.add_header("User-Agent", "InformeObra/1.0")')
new_api.append('                ctx = ssl.create_default_context()')
new_api.append('                with urllib.request.urlopen(req, timeout=15, context=ctx) as resp:')
new_api.append('                    raw = json.loads(resp.read().decode("utf-8"))')
new_api.append('                tag = raw.get("tag_name", "")')
new_api.append('                asset = next((a for a in raw.get("assets", [])')
new_api.append('                              if a.get("name", "").endswith(".zip")), None)')
new_api.append('                data = {')
new_api.append('                    "tag": tag,')
new_api.append('                    "nombre": raw.get("name", ""),')
new_api.append('                    "publicada": raw.get("published_at", ""),')
new_api.append('                    "asset": asset.get("name") if asset else None,')
new_api.append('                    "url": asset.get("browser_download_url") if asset else None,')
new_api.append('                }')
new_api.append('            except Exception as e:')
new_api.append('                return jsonify({"disponible": None, "error": str(e),')
new_api.append('                                "version_actual": local_v}), 502')
new_api.append('')
new_api.append('        hay_nueva = _vt(tag) > _vt(local_v)')
new_api.append('        return jsonify({')
new_api.append('            "disponible": bool(hay_nueva), "tag": tag,')
new_api.append('            "nombre": data.get("nombre", ""),')
new_api.append('            "publicada": data.get("publicada", ""),')
new_api.append('            "asset": data.get("asset"),')
new_api.append('            "url": data.get("url"),')
new_api.append('            "version_actual": local_v,')
new_api.append('        })')
new_api.append('')

code = code[:idx1] + "\n".join(new_api) + code[idx2:]
print("[OK] api_actualizacion parcheado")

# 4. Reemplazar aplicar_actualizacion
idx3 = code.find("def aplicar_actualizacion()")
idx4 = code.find("def progreso_actualizacion()")
if idx3 == -1 or idx4 == -1:
    print("ERROR: No se encontro aplicar_actualizacion")
    sys.exit(1)

new_apply = []
new_apply.append('def aplicar_actualizacion():')
new_apply.append('        """Descarga e instala actualizacion. gh CLI o REST API."""')
new_apply.append('        if not es_admin_actual():')
new_apply.append('            return jsonify({"error": "No autorizado"}), 403')
new_apply.append('        try:')
new_apply.append('            import subprocess, tempfile, urllib.request, ssl')
new_apply.append('            root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))')
new_apply.append('            ps1 = os.path.join(root, "actualizar.ps1")')
new_apply.append('            repo = app.config.get("INFORME_REPO", "jacj01/informe-mensual-obra")')
new_apply.append('            local_v = app.config.get("INFORME_VERSION", "1.0.0")')
new_apply.append('')
new_apply.append('            tag = ""')
new_apply.append('            try:')
new_apply.append('                cmd = ["gh", "-R", repo, "release", "view", "--json", "tagName"]')
new_apply.append('                out = subprocess.run(cmd, capture_output=True, text=True, timeout=15,')
new_apply.append('                                     creationflags=0x08000000)')
new_apply.append('                if out.returncode == 0:')
new_apply.append('                    tag = json.loads(out.stdout).get("tagName", "")')
new_apply.append('            except Exception:')
new_apply.append('                pass')
new_apply.append('            if not tag:')
new_apply.append('                try:')
new_apply.append('                    api_url = "https://api.github.com/repos/" + repo + "/releases/latest"')
new_apply.append('                    req = urllib.request.Request(api_url)')
new_apply.append('                    req.add_header("Accept", "application/vnd.github+json")')
new_apply.append('                    req.add_header("User-Agent", "InformeObra/1.0")')
new_apply.append('                    ctx = ssl.create_default_context()')
new_apply.append('                    with urllib.request.urlopen(req, timeout=15, context=ctx) as resp:')
new_apply.append('                        tag = json.loads(resp.read().decode()).get("tag_name", "")')
new_apply.append('                except Exception:')
new_apply.append('                    pass')
new_apply.append('')
new_apply.append('            if not tag:')
new_apply.append('                return jsonify({"ok": False, "error": "No se pudo conectar con GitHub."}), 400')
new_apply.append('')
new_apply.append('            tmp_dir = tempfile.mkdtemp(prefix="informe_upd_")')
new_apply.append('            zip_path = None')
new_apply.append('            try:')
new_apply.append('                r = subprocess.run(["gh", "-R", repo, "release", "download", tag,')
new_apply.append('                                    "--pattern", "*.zip", "--dir", tmp_dir],')
new_apply.append('                                   capture_output=True, text=True, timeout=120,')
new_apply.append('                                   creationflags=0x08000000)')
new_apply.append('                if r.returncode == 0:')
new_apply.append('                    zips = [f for f in os.listdir(tmp_dir) if f.endswith(".zip")]')
new_apply.append('                    if zips:')
new_apply.append('                        zip_path = os.path.join(tmp_dir, zips[0])')
new_apply.append('            except Exception:')
new_apply.append('                zip_path = None')
new_apply.append('            if not zip_path:')
new_apply.append('                try:')
new_apply.append('                    api_dl = "https://api.github.com/repos/" + repo + "/releases/tags/" + tag')
new_apply.append('                    req2 = urllib.request.Request(api_dl)')
new_apply.append('                    req2.add_header("Accept", "application/vnd.github+json")')
new_apply.append('                    req2.add_header("User-Agent", "InformeObra/1.0")')
new_apply.append('                    ctx2 = ssl.create_default_context()')
new_apply.append('                    with urllib.request.urlopen(req2, timeout=15, context=ctx2) as resp2:')
new_apply.append('                        rel = json.loads(resp2.read().decode())')
new_apply.append('                    zip_asset = next((a for a in rel.get("assets", [])')
new_apply.append('                                      if a.get("name", "").endswith(".zip")), None)')
new_apply.append('                    if zip_asset:')
new_apply.append('                        dl_url = zip_asset.get("browser_download_url")')
new_apply.append('                        req3 = urllib.request.Request(dl_url)')
new_apply.append('                        req3.add_header("User-Agent", "InformeObra/1.0")')
new_apply.append('                        with urllib.request.urlopen(req3, timeout=120, context=ctx2) as dl:')
new_apply.append('                            zip_path = os.path.join(tmp_dir, zip_asset["name"])')
new_apply.append('                            with open(zip_path, "wb") as f:')
new_apply.append('                                while True:')
new_apply.append('                                    chunk = dl.read(65536)')
new_apply.append('                                    if not chunk:')
new_apply.append('                                        break')
new_apply.append('                                    f.write(chunk)')
new_apply.append('                except Exception:')
new_apply.append('                    zip_path = None')
new_apply.append('')
new_apply.append('            if not zip_path:')
new_apply.append('                return jsonify({"ok": False, "error": "No se pudo descargar."}), 400')
new_apply.append('')
new_apply.append('            ps_args = ["powershell.exe", "-NoProfile", "-WindowStyle", "Hidden",')
new_apply.append('                       "-ExecutionPolicy", "Bypass", "-File", ps1, "-Instalar",')
new_apply.append('                       "-VersionLocal", local_v, "-ZipFile", zip_path]')
new_apply.append('            subprocess.Popen(ps_args, cwd=root,')
new_apply.append('                             creationflags=0x08000800,')
new_apply.append('                             stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL,')
new_apply.append('                             stderr=subprocess.DEVNULL)')
new_apply.append('            return jsonify({"ok": True, "msg": "Actualizacion iniciada."})')
new_apply.append('        except Exception as e:')
new_apply.append('            return jsonify({"ok": False, "error": str(e)}), 500')
new_apply.append('')

code = code[:idx3] + "\n".join(new_apply) + code[idx4:]
print("[OK] aplicar_actualizacion parcheado")

# 5. Guardar
with open(APP_PY, "w", encoding="utf-8") as f:
    f.write(code)

# 6. Parche base.html (error handling)
with open(BASE_HTML, "r", encoding="utf-8") as f:
    html = f.read()

old_h = "if (d.disponible) {"
new_h = ("if (d.error) {\n"
         "            document.getElementById('updErrorMsg').textContent = 'Error: ' + d.error;\n"
         "            _updShow('updEstadoError');\n"
         "            _updBtn('updBtnInstalar', false);\n"
         "          } else if (d.disponible) {")
if old_h in html:
    html = html.replace(old_h, new_h, 1)
    with open(BASE_HTML, "w", encoding="utf-8") as f:
        f.write(html)
    print("[OK] base.html parcheado")
else:
    print("[SKIP] base.html ya parcheado")

# 7. Verificar regex
import re
test = re.search(r"v?(\d+\.\d+\.\d+)", "v1.1.0-f51baf3")
if test:
    print("[OK] Regex funciona: v1.1.0-f51baf3 -> " + test.group(1))
else:
    print("[ERROR] Regex NO funciona!")

print()
print("Listo. Reinicie el servidor.")
